//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK
    {
        public decimal ID_CUS { get; set; }
        public decimal ID_LESSION { get; set; }
        public Nullable<decimal> ID_COURCE { get; set; }
    }
}
