//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMT
    {
        public decimal ID_CMT { get; set; }
        public Nullable<decimal> ID_LESS { get; set; }
        public string CMT1 { get; set; }
    
        public virtual LESSION LESSION { get; set; }
    }
}
