//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE
    {
        public COURSE()
        {
            this.LESSIONs = new HashSet<LESSION>();
        }
    
        public decimal ID_COURSE { get; set; }
        public string NAME { get; set; }
        public string IMG { get; set; }
    
        public virtual ICollection<LESSION> LESSIONs { get; set; }
    }
}
