//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public CUSTOMER()
        {
            this.LESSIONs = new HashSet<LESSION>();
        }
    
        public decimal ID_CUS { get; set; }
        public string NAME_CUS { get; set; }
        public string EMAIL_CUS { get; set; }
        public string PHONE_CUS { get; set; }
        public Nullable<System.DateTime> DATE_CUS { get; set; }
        public string USER_NAME { get; set; }
        public Nullable<decimal> ROLE { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual ICollection<LESSION> LESSIONs { get; set; }
    }
}
