//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LESSION
    {
        public LESSION()
        {
            this.CMTs = new HashSet<CMT>();
            this.CUSTOMERs = new HashSet<CUSTOMER>();
        }
    
        public decimal ID_LESSION { get; set; }
        public string NAME_LESSION { get; set; }
        public string LINK_VIDEO { get; set; }
        public Nullable<decimal> ID_COURSE { get; set; }
    
        public virtual ICollection<CMT> CMTs { get; set; }
        public virtual COURSE COURSE { get; set; }
        public virtual ICollection<CUSTOMER> CUSTOMERs { get; set; }
    }
}
